<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1676540190704' stop='1676540250714'>
    <name>My Login application</name>
    <title>My Login application</title>
    <test-cases>
        <test-case start='1676540190705' status='broken' stop='1676540250712'>
            <name>"before all" hook for My Login application</name>
            <title>"before all" hook for My Login application</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-110.0.5481.97'/>
            </parameters>
            <steps>
                <step start='1676540190711' status='broken' stop='1676540250711'>
                    <name>POST /session/:sessionId/url</name>
                    <title>POST /session/:sessionId/url</title>
                    <attachments>
                        <attachment title='Request' source='c40ce943-edb8-41d8-bce4-8cb6e63b318d-attachment.json' type='application/json' size='45'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Timeout of 60000ms exceeded. The execution in the test "My Login application "before all" hook for "should login with valid credentials"" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (C:\Users\DataOn-User\Documents\automation\test\specs\example.e2e.js)</message>
                <stack-trace>Error: Timeout of 60000ms exceeded. The execution in the test "My Login application "before all" hook for "should login with valid credentials"" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (C:\Users\DataOn-User\Documents\automation\test\specs\example.e2e.js)
                    at createTimeoutError (C:\Users\DataOn-User\Documents\automation\node_modules\mocha\lib\errors.js:498:15)
                    at Hook.Runnable._timeoutError (C:\Users\DataOn-User\Documents\automation\node_modules\mocha\lib\runnable.js:431:10)
                    at Timeout.&lt;anonymous> (C:\Users\DataOn-User\Documents\automation\node_modules\mocha\lib\runnable.js:246:24)
                    at listOnTimeout (node:internal/timers:559:17)
                    at processTimers (node:internal/timers:502:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>